version: "2.6"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "todo-app"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - todo-app-db:/var/lib/mysql

volumes:
  todo-app-db:
